# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
      - source: scripts/
        dest: scripts/
        deleteOrphaned: true
      - source: assets/
        dest: assets/
        deleteOrphaned: true
      - source: index.Rmd
        dest: index.Rmd
      - source: About.Rmd
        dest: About.Rmd
      - source: config_automation.yml
        dest: config_automation.yml
      - source: References.Rmd
        dest: References.Rmd
      - source: book.bib
        dest: book.bib
      - source: _bookdown.yml
        dest: _bookdown.yml
      - source: _output.yml
        dest: _output.yml
      - source: .github/ISSUE_TEMPLATE/course-problem-report.md
        dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      - source: .github/ISSUE_TEMPLATE/course-content-add.md
        dest: .github/ISSUE_TEMPLATE/course-content-add.md
      - source: scripts/make_screenshots.R
        dest: scripts/make_screenshots.R
      - source: scripts/spell-check.R
        dest: scripts/spell-check.R
      - source: scripts/git_repo_check.R
        dest: scripts/git_repo_check.R
      - source: code_of_conduct.md
        dest: code_of_conduct.md
  # Repositories to receive changes
    repos: |
      datatrail-jhu/cds_intro
      datatrail-jhu/cds_chromebookintro
      datatrail-jhu/cds_googlecloud
      datatrail-jhu/cds_fileorganization
      datatrail-jhu/cds_githubbasics
      datatrail-jhu/cds_R
      datatrail-jhu/cds_datacleaning
      datatrail-jhu/cds_dataviz
      datatrail-jhu/cds_dataanalysis
      datatrail-jhu/cds_dsjob
      datatrail-jhu/cds_dataproducts
      datatrail-jhu/cds_finalproject
###ADD NEW REPO HERE following the format above#
